#include "vars.h"
int reservationCount = 0;
int scheduleCount = 0;
int movieCount = 0;
char movieNames[100][500];
int importSchedule[500][6];
int importReservations[5000][7];
double totals[5000];
char userNames[5000][2][50];
char userFirstName[500];
char userLastName[500];
double total = 0.00;
int orderReview = 0;
int adminAccess = 0;
int counting[500];
int count = 0;
char food[9][2][50];
int foodPrices[9];
int foodItems = 0;
char movieMonth[12][50] = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
char movieTimes[5][10] = {"16:00", "18:00", "20:00", "22:00", "24:00"};
char rowLetters[26] = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'};
char add = 'Y';
int itemCounter = 0;
int itemsSelected[50][3];
int adminOption = 0;
int userMovieToSave;
int userMonthToSave;
int userDayToSave;
int userTimeToSave;
int orderNumber;
int rows;
int seats;
int userMovieChoice;
int userDateChoice;
int userSeatChoice;
char userRowChoiceLetter;
int userRowChoice;
int userFoodChoice;
